### ISSUE TITLE
Can't compile on windows

### ISSUE THREAD

**Issue by snakevash** [Mitranim/jisp#39]
I found jisp can't compile on window.(win7)
Is there any one same with me?
When I command `jisp -c <file>`,then it hold on, nothing can done.

**Comment by mitranim** [comment]
Turned out to be because of a typo in `command.jisp`. Published an update. Please try 0.3.3 and see if it fixes your problem.

**Comment by mitranim** [comment]
Also, please be aware that compilation may fail if the source file contains invalid symbols, which is particularly likely if it's created by Notepad. Make sure to use a sensible editor like Sublime Text or Notepad++.

**Comment by snakevash** [comment]
After update, it can work.
By the way , I like jisp. I think it more better than clojurescript. cljs is too heavy.
Look forward to 0.4.0.
^_^

**Comment by mitranim** [comment]
Glad this helped, and glad you like it. :)
